game-debate.com, gamersheroes.com, keenspot.com
NanoAdblockerLab/NanoContrib pull request #126
Opened 2020-07-02 12:19 UTC by DandelionSprout

* Fix https://github.com/NanoMeow/QuickReports/issues/4226

Example pages:

```
! https://www.game-debate.com/blog/17014/undervolting-i7-4770k
game-debate.com##.bxz:has(> div[id^=div-gpt-ad])
! http://www.gamersheroes.com/game-guides/where-to-play-blackjack-in-red-dead-redemption-2/
||disqusservice.com/iframe/fallback^$subdocument,domain=gamersheroes.com
! http://keenspot.com/
keenspot.com###ad
! http://fallouttoyworks.keenspot.com/
fallouttoyworks.keenspot.com###atomekarect
fallouttoyworks.keenspot.com###atomekalead
fallouttoyworks.keenspot.com###atomekasky

! https://github.com/NanoMeow/QuickReports/issues/4226
! http://brawlinthefamily.keenspot.com/comic/498-thwompstrategy/
! http://countyoursheep.keenspot.com/
! http://nopinkponies.keenspot.com/
! http://thelounge.keenspot.com/
keenspot.com##div[id^="KS_G"]
```

2020-07-02 14:37 UTC, jspenguin2017 commented on dist/placeholder-buster.txt
> +keenspot.com##div[id^="KS_G"]
Please fix these linting errors: 
```
[WRN] 2030 : Rules for a domain is split into multiple sections
[WRN] 2035 : Rules for a domain is split into multiple sections
```

2020-07-03 14:48 UTC, DandelionSprout commented
Oh, right. I had forgot about fixing this. Give me some minutes.

2020-07-03 18:05 UTC, jspenguin2017 requested changes
- `fallouttoyworks.keenspot.com` has another section on line `705`, please merge them
- Please provide test links for all rules

2020-07-03 18:06 UTC, DandelionSprout commented
Will do. Give me 6min.

2020-07-03 18:13 UTC, DandelionSprout commented
Should hopefully have been done now.

2020-07-03 18:57 UTC, merged

2020-07-03 18:57 UTC, jspenguin2017 commented
`https://www.game-debate.com/blog/17014/undervolting-i7-4770k`

2020-07-03 18:57 UTC, jspenguin2017 commented
`http://www.gamersheroes.com/game-guides/where-to-play-blackjack-in-red-dead-redemption-2/`

2020-07-03 18:57 UTC, jspenguin2017 commented
```
http://keenspot.com/
http://brawlinthefamily.keenspot.com/comic/498-thwompstrategy/
http://countyoursheep.keenspot.com/
http://nopinkponies.keenspot.com/
http://thelounge.keenspot.com/
```

2020-07-03 18:58 UTC, jspenguin2017 commented
`http://fallouttoyworks.keenspot.com/`

2020-07-03 18:58 UTC, jspenguin2017 commented
`https://news.avclub.com/and-now-here-s-an-exhaustive-examination-of-every-job-h-1844245920`

2020-07-03 18:58 UTC, jspenguin2017 commented
`https://bleedingcool.com/comics/marvel-comics-announces-upcoming-knull-crossover-event/`

2020-07-03 18:58 UTC, jspenguin2017 commented
`https://www.freem.ne.jp/win/game/21911`